# Generated by Django 2.2.19 on 2022-08-27 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['pub_date'], 'verbose_name': 'Комментарий к отзыву'},
        ),
        migrations.AlterModelOptions(
            name='reviews',
            options={'ordering': ['pub_date'], 'verbose_name': 'Отзыв'},
        ),
    ]
