# Generated by Django 2.2.19 on 2022-08-28 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_title_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titlegenre',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reviews.Genres'),
        ),
    ]
