# Generated by Django 2.2.16 on 2022-08-28 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0011_title_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='review',
        ),
    ]
