# Generated by Django 2.2.16 on 2022-08-30 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0017_auto_20220830_1851'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
